/* Use a disposable workspace on port 8011. The semantic model must be installed. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const base = process.env.BASE_URL || 'http://127.0.0.1:8011';
  const out = process.env.QA_DIR || 'data/qa';
  fs.mkdirSync(out, { recursive: true });
  try {
    await page.goto(base);
    await page.click('#load-demo');
    await page.waitForFunction(() => document.getElementById('stat-docs').textContent === '12', { timeout: 60000 });
    await page.fill('#question', 'How many search requests per minute are permitted?');
    await page.click('#ask-button');
    await page.waitForSelector('#answer-body .citation', { timeout: 60000 });
    assert.match(await page.locator('#answer-body').innerText(), /120/);
    assert.equal(await page.locator('#answer-badge').innerText(), 'LOCAL EXCERPTS');
    await page.locator('#answer-body .citation').first().click();
    await page.waitForSelector('#source-dialog[open]');
    assert.match(await page.locator('#source-content').innerText(), /120/);
    await page.click('[data-close="source-dialog"]');
    const downloadPromise = page.waitForEvent('download');
    await page.click('#download-trace');
    assert.match((await downloadPromise).suggestedFilename(), /trace.*json$/);
    await page.screenshot({ path: path.join(out, 'answer.png'), fullPage: true });
    await page.selectOption('#category-filter', 'Operations');
    await page.waitForFunction(() => !document.getElementById('ask-button').disabled);
    assert.ok((await page.locator('#passage-list').innerText()).includes('Operations'));
    assert.ok(!(await page.locator('#passage-list').innerText()).includes('Engineering ·'));
    await page.selectOption('#category-filter', '');
    await page.waitForFunction(() => !document.getElementById('ask-button').disabled);
    await page.fill('#question', 'What temperature should a chocolate cake bake at?');
    await page.click('#ask-button');
    await page.waitForFunction(() => document.getElementById('answer-badge').textContent === 'ABSTAINED');
    await page.click('[data-page="library"]');
    await page.setInputFiles('#upload-file', { name: 'invalid.txt', mimeType: 'text/plain', buffer: Buffer.from([0xff, 0xfe]) });
    await page.click('#upload-button');
    await page.waitForSelector('#notice.error');
    assert.match(await page.locator('#notice').innerText(), /UTF-8/);
    const upload = async (name, text) => {
      await page.setInputFiles('#upload-file', { name, mimeType: 'text/markdown', buffer: Buffer.from(text) });
      await page.fill('#upload-title', 'Lifecycle test');
      await page.fill('#upload-category', 'Testing');
      await page.click('#upload-button');
      await page.waitForFunction(() => document.getElementById('notice').textContent.includes('Indexed Lifecycle test'));
    };
    await upload('lifecycle.md', '# Retention\n\nThe amber retention interval is 90 days.');
    let row = page.locator('.document-row').filter({ hasText: 'Lifecycle test' });
    await row.locator('[data-replace]').click();
    await page.fill('#replacement-version', '2.0');
    await page.setInputFiles('#replacement-file', { name: 'lifecycle.md', mimeType: 'text/markdown', buffer: Buffer.from('# Retention\n\nThe violet retention interval is 30 days.') });
    await page.click('#replace-button');
    await page.waitForFunction(() => document.getElementById('notice').textContent.includes('Version 2.0 is now current'));
    await page.check('#show-archived');
    assert.equal(await page.locator('.document-row').filter({ hasText: 'Lifecycle test' }).count(), 2);
    await page.click('[data-page="ask"]');
    await page.selectOption('#retrieval-mode', 'keyword');
    await page.fill('#question', 'amber');
    await page.click('#intent-search');
    await page.click('#ask-button');
    await page.waitForSelector('#query-results:visible');
    assert.match(await page.locator('#passage-list').innerText(), /No passages found/);
    await page.check('#include-archived');
    await page.waitForFunction(() => document.getElementById('passage-list').textContent.includes('90 days'));
    assert.match(await page.locator('#passage-list').innerText(), /Archived/);
    await page.click('[data-page="library"]');
    row = page.locator('.document-row').filter({ hasText: 'Lifecycle test' }).filter({ hasText: 'v2.0' });
    await row.locator('[data-delete]').click();
    await page.click('#confirm-delete');
    await page.waitForFunction(() => document.getElementById('notice').textContent.includes('Selected version deleted'));
    await page.click('[data-page="history"]');
    await page.waitForFunction(() => document.getElementById('history-list').textContent.includes('No saved questions'));
    assert.match(await page.locator('#history-list').innerText(), /No saved questions/);
    await page.click('[data-page="evaluation"]');
    await page.click('#run-evaluation');
    await page.waitForSelector('#eval-report:visible', { timeout: 120000 });
    assert.equal(await page.locator('#evaluation-table tbody tr').count(), 4);
    assert.equal(await page.locator('#question-results details').count(), 50);
    await page.selectOption('#eval-split', 'dev');
    assert.equal(await page.locator('#question-results details').count(), 16);
    await page.screenshot({ path: path.join(out, 'evaluation.png'), fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    for (const tab of ['ask', 'library', 'evaluation', 'history', 'guide']) {
      await page.click(`[data-page="${tab}"]`);
      await page.waitForTimeout(150);
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `${tab} must fit mobile viewport`);
      await page.screenshot({ path: path.join(out, `mobile-${tab}.png`), fullPage: true });
    }
    assert.deepEqual(errors, []);
    console.log('PASS: sample ingestion, semantic answers, citations, trace download, filters, abstention, invalid upload, version replacement, archived search, deletion cleanup, real-model evaluation, and five mobile pages.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
